"""
08 — Database: SQLModel Table Definitions

SQLModel combines:
- Pydantic -> data validation / parsing
- SQLAlchemy -> ORM / database mapping

This means the same class can be used both:
1. as a Python data model
2. as a database table definition

Important:
- table=True  -> create a real database table
- without it  -> plain data/schema model only
"""

from sqlmodel import Field, Relationship, SQLModel


class Team(SQLModel, table=True):
    """A team that heroes can belong to."""
    # Primary key:
    # default=None allows the database to generate the id automatically.
    id: int | None = Field(default=None, primary_key=True)
    # Regular required column.
    name: str

    # One-to-many relationship: one team → many heroes
    # Relationship only exists at the ORM/Python level.
    # It is NOT a physical database column.
    #
    # back_populates connects this attribute with Hero.team
    # so both sides stay synchronized in ORM usage.
    heroes: list["Hero"] = Relationship(back_populates="team")


class Hero(SQLModel, table=True):
    """A hero with a name, power, optional age, and optional team."""
    # Primary key, auto-generated by the database when omitted.
    id: int | None = Field(default=None, primary_key=True)
    # index=True creates a database index for faster lookups/searches
    # on the name column.
    name: str = Field(index=True)
    # Required column storing the hero's main ability.
    power: str
    # Optional column:
    # if no value is given, NULL will be stored in the database.
    age: int | None = None

    # Foreign key column:
    # stores the id of the related team.
    # "team.id" means:
    #   table name = team
    #   referenced column = id
    #
    # Because this field is optional, a hero may exist without a team.
    team_id: int | None = Field(default=None, foreign_key="team.id")
    # ORM relationship to access the related Team object directly.
    # This is more convenient than working only with team_id.
    #
    # Example:
    #   hero.team -> returns the Team object
    team: Team | None = Relationship(back_populates="heroes")


class HeroUpdate(SQLModel):
    """Schema for partial updates — all fields optional."""

    # All fields are optional so the client can send only
    # the values that need to be changed.
    #
    # Example:
    #   {"power": "Flight"}
    # updates only the power field without affecting the others.
    name: str | None = None
    power: str | None = None
    age: int | None = None
    team_id: int | None = None
